<a href="https://colab.research.google.com/github/codewithadityard/employee-attrition-prediction/blob/main/01_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## EDA

In [ ]:
df=pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [ ]:
pip install -U imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\admin\ml2\envs\pytorch\lib\site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (2.2.6)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (1.7.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\admin\ml2\envs\pytorch\lib\site-packages (from imbalanced-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

# df["Attrition"] obj --> int

In [ ]:
df['Attrition']=np.where(df['Attrition']=='Yes',1,0)

In [ ]:
df["Attrition"].value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

## df["BusinessTravle"] obj --> int using (get_ dummies)

In [ ]:
df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [ ]:
df_buisness_travel=pd.get_dummies(df["BusinessTravel"],drop_first=True,dtype=int)

In [ ]:
df_buisness_travel

      Travel_Frequently  Travel_Rarely
0                     0              1
1                     1              0
2                     0              1
3                     1              0
4                     0              1
...                 ...            ...
1465                  1              0
1466                  0              1
1467                  0              1
1468                  1              0
1469                  0              1

[1470 rows x 2 columns]

## df["Deapartment"]  obj --> int (one hot encoder)

In [ ]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoder_department=encoder.fit_transform(df[["Department"]]).toarray()
df_department=pd.DataFrame(encoder_department,columns=encoder.get_feature_names_out())

In [ ]:
df_department

,Department_Human Resources,Department_Research & Development,Department_Sales
0,0.0,0.0,1.0
1,0.0,1.0,0.0
2,0.0,1.0,0.0
3,0.0,1.0,0.0
4,0.0,1.0,0.0
...,...,...,...
1465,0.0,1.0,0.0
1466,0.0,1.0,0.0
1467,0.0,1.0,0.0
1468,0.0,0.0,1.0
1469,0.0,1.0,0.0

## df[EducationField] obj-->int (get_dummies)

In [ ]:
df['EducationField'].value_counts()

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

In [ ]:
df_education_field=pd.get_dummies(df["EducationField"],drop_first=True,dtype=int)
df_education_field

      Life Sciences  Marketing  Medical  Other  Technical Degree
0                 1          0        0      0                 0
1                 1          0        0      0                 0
2                 0          0        0      1                 0
3                 1          0        0      0                 0
4                 0          0        1      0                 0
...             ...        ...      ...    ...               ...
1465              0          0        1      0                 0
1466              0          0        1      0                 0
1467              1          0        0      0                 0
1468              0          0        1      0                 0
1469              0          0        1      0                 0

[1470 rows x 5 columns]

## df[Gender]  str--> int

In [ ]:
df['Gender'].value_counts()

Gender
Male      882
Female    588
Name: count, dtype: int64

In [ ]:
df['Gender']=np.where(df['Gender']=="Male",1,0)

## df[JobRole]  obj--> int (get_dummies)

In [ ]:
df["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [ ]:
df_job_role=pd.get_dummies(df["JobRole"],drop_first=True,dtype=int)

In [ ]:
df_job_role

,Human Resources,Laboratory Technician,Manager,Manufacturing Director,Research Director,Research Scientist,Sales Executive,Sales Representative
0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0
4,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
1465,0,1,0,0,0,0,0,0
1466,0,0,0,0,0,0,0,0
1467,0,0,0,1,0,0,0,0
1468,0,0,0,0,0,0,1,0
1469,0,1,0,0,0,0,0,0

In [ ]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [ ]:
encoded_marital_status=encoder.fit_transform(df[["MaritalStatus"]]).toarray()
df_material_status=pd.DataFrame(encoded_marital_status,columns=encoder.get_feature_names_out())

In [ ]:
df_material_status

      MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single
0                        0.0                    0.0                   1.0
1                        0.0                    1.0                   0.0
2                        0.0                    0.0                   1.0
3                        0.0                    1.0                   0.0
4                        0.0                    1.0                   0.0
...                      ...                    ...                   ...
1465                     0.0                    1.0                   0.0
1466                     0.0                    1.0                   0.0
1467                     0.0                    1.0                   0.0
1468                     0.0                    1.0                   0.0
1469                     0.0                    1.0                   0.0

[1470 rows x 3 columns]

In [ ]:
df["Over18"].value_counts()
df.drop("Over18",axis=1,inplace=True)

In [ ]:
df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [ ]:
df['OverTime']=np.where(df['OverTime']=="Yes",1,0)

In [ ]:
df=pd.concat([df,df_buisness_travel,df_department,df_education_field,df_job_role],axis=1)

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,Other,Technical Degree,Human Resources,Laboratory Technician,Manager,Manufacturing Director,Research Director,Research Scientist,Sales Executive,Sales Representative
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,0,0,0,0,0,0,0,0,1,0
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,0,0,0,0,0,0,0,1,0,0
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,1,0,0,1,0,0,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,0,0,0,0,0,0,0,1,0,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Travel_Frequently', 'Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'Life Sciences', 'Marketing', 'Medical', 'Other',
       'Technical Degree', 'Human Resources', 'Laboratory Technician',
       'Manager', 'Manufacturing Director', 'Research Director',
       'Research Scientist', 'Sales Executive', 'Sales Representative'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 52 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   Attrition                          1470 non-null   int64
 2   BusinessTravel                     1470 non-null   object
 3   DailyRate                          1470 non-null   int64
 4   Department                         1470 non-null   object
 5   DistanceFromHome                   1470 non-null   int64
 6   Education                          1470 non-null   int64
 7   EducationField                     1470 non-null   object
 8   EmployeeCount                      1470 non-null   int64
 9   EmployeeNumber                     1470 non-null   int64
 10  EnvironmentSatisfaction            1470 non-null   int64
 11  Gender                             1470 non-null   int64
 12  HourlyRate                         1470 non-null   int64
 13  JobInvolvement                     1470 non-null   int64
 14  JobLevel                           1470 non-null   int64
 15  JobRole                            1470 non-null   object
 16  JobSatisfaction                    1470 non-null   int64
 17  MaritalStatus                      1470 non-null   object
 18  MonthlyIncome                      1470 non-null   int64
 19  MonthlyRate                        1470 non-null   int64
 20  NumCompaniesWorked                 1470 non-null   int64
 21  OverTime                           1470 non-null   int64
 22  PercentSalaryHike                  1470 non-null   int64
 23  PerformanceRating                  1470 non-null   int64
 24  RelationshipSatisfaction           1470 non-null   int64
 25  StandardHours                      1470 non-null   int64
 26  StockOptionLevel                   1470 non-null   int64
 27  TotalWorkingYears                  1470 non-null   int64
 28  TrainingTimesLastYear              1470 non-null   int64
 29  WorkLifeBalance                    1470 non-null   int64
 30  YearsAtCompany                     1470 non-null   int64
 31  YearsInCurrentRole                 1470 non-null   int64
 32  YearsSinceLastPromotion            1470 non-null   int64
 33  YearsWithCurrManager               1470 non-null   int64
 34  Travel_Frequently                  1470 non-null   int64
 35  Travel_Rarely                      1470 non-null   int64
 36  Department_Human Resources         1470 non-null   float64
 37  Department_Research & Development  1470 non-null   float64
 38  Department_Sales                   1470 non-null   float64
 39  Life Sciences                      1470 non-null   int64
 40  Marketing                          1470 non-null   int64
 41  Medical                            1470 non-null   int64
 42  Other                              1470 non-null   int64
 43  Technical Degree                   1470 non-null   int64
 44  Human Resources                    1470 non-null   int64
 45  Laboratory Technician              1470 non-null   int64
 46  Manager                            1470 non-null   int64
 47  Manufacturing Director             1470 non-null   int64
 48  Research Director                  1470 non-null   int64
 49  Research Scientist                 1470 non-null   int64
 50  Sales Executive                    1470 non-null   int64
 51  Sales Representative               1470 non-null   int64
dtypes: float64(3), int64(44), object(5)
memory usage: 597.3+ KB

In [ ]:
df.drop(["BusinessTravel","Department","EducationField","JobRole","MaritalStatus"],axis=1,inplace=True)

In [ ]:
df.columns

Index(['Age', 'Attrition', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'Travel_Frequently', 'Travel_Rarely', 'Department_Human Resources',
       'Department_Research & Development', 'Department_Sales',
       'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree',
       'Human Resources', 'Laboratory Technician', 'Manager',
       'Manufacturing Director', 'Research Director', 'Research Scientist',
       'Sales Executive', 'Sales Representative'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 47 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   Attrition                          1470 non-null   int64
 2   DailyRate                          1470 non-null   int64
 3   DistanceFromHome                   1470 non-null   int64
 4   Education                          1470 non-null   int64
 5   EmployeeCount                      1470 non-null   int64
 6   EmployeeNumber                     1470 non-null   int64
 7   EnvironmentSatisfaction            1470 non-null   int64
 8   Gender                             1470 non-null   int64
 9   HourlyRate                         1470 non-null   int64
 10  JobInvolvement                     1470 non-null   int64
 11  JobLevel                           1470 non-null   int64
 12  JobSatisfaction                    1470 non-null   int64
 13  MonthlyIncome                      1470 non-null   int64
 14  MonthlyRate                        1470 non-null   int64
 15  NumCompaniesWorked                 1470 non-null   int64
 16  OverTime                           1470 non-null   int64
 17  PercentSalaryHike                  1470 non-null   int64
 18  PerformanceRating                  1470 non-null   int64
 19  RelationshipSatisfaction           1470 non-null   int64
 20  StandardHours                      1470 non-null   int64
 21  StockOptionLevel                   1470 non-null   int64
 22  TotalWorkingYears                  1470 non-null   int64
 23  TrainingTimesLastYear              1470 non-null   int64
 24  WorkLifeBalance                    1470 non-null   int64
 25  YearsAtCompany                     1470 non-null   int64
 26  YearsInCurrentRole                 1470 non-null   int64
 27  YearsSinceLastPromotion            1470 non-null   int64
 28  YearsWithCurrManager               1470 non-null   int64
 29  Travel_Frequently                  1470 non-null   int64
 30  Travel_Rarely                      1470 non-null   int64
 31  Department_Human Resources         1470 non-null   float64
 32  Department_Research & Development  1470 non-null   float64
 33  Department_Sales                   1470 non-null   float64
 34  Life Sciences                      1470 non-null   int64
 35  Marketing                          1470 non-null   int64
 36  Medical                            1470 non-null   int64
 37  Other                              1470 non-null   int64
 38  Technical Degree                   1470 non-null   int64
 39  Human Resources                    1470 non-null   int64
 40  Laboratory Technician              1470 non-null   int64
 41  Manager                            1470 non-null   int64
 42  Manufacturing Director             1470 non-null   int64
 43  Research Director                  1470 non-null   int64
 44  Research Scientist                 1470 non-null   int64
 45  Sales Executive                    1470 non-null   int64
 46  Sales Representative               1470 non-null   int64
dtypes: float64(3), int64(44)
memory usage: 539.9 KB

In [ ]:
df.to_csv("cleaned_file_employee.csv",index=False)